BINDIR = /usr/local/bin

BASHSCRIPTS = build jk-mount-usb mychess mygo jk-umount-usb ogg2mp3 jk-backup-work jk-start-vnc jk-stop-vnc jk-git-add jk-git-merge mybench jk-run-virtual

default:
	true


install:
	mkdir -p -m 755 $(BINDIR)
	cp $(BASHSCRIPTS) $(BINDIR)
